CC=g++
CFLAGS=-Wall -std=c++11 -std=gnu++11
LDFLAGS=-lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
SOURCES=Game.cpp main.cpp
EXECUTABLE=run

all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(EXECUTABLE) $(LDFLAGS)
# g++ -Wall YOURFILENAME.cpp -o SDL_Test -lSDL2

